### ISSUE TITLE
Struggling to quantize Llama-3.1-70b -  OOM/linalg.Cholesky issue 

### ISSUE THREAD

**Issue by lulmer** [vllm-project/llm-compressor#109]
**Describe the bug**
Hello the vLLM team, thank you for your outstanding work. I think llm-compressor is really filling a need : a one simple unified quant franework for vLLM. 

So the bug I am encountering is the following. 
When trying to quantize llama3.1-70b on the int4 format (W4A16) I always get CUDA OOM right after the calibration epoch is finished. I also tried setting `sequential_update=True` in `oneshot` function and I got a more informative log (see bellow).

**Expected behavior**
The model to be successfully quantised in int4 (W4A16), but I also suspect the int8 (W8A8) script to suffer from the same problem. 

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]: Debian 12 (Bookworm)
2. Python version [e.g. 3.7]: 3.11.9
3. LLM Compressor version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.1.0
4. ML framework version(s) [e.g. torch 2.3.1]: 2.3.1
5. Other Python package versions [e.g. vLLM, compressed-tensors, numpy, ONNX]: vLLM 0.5.3.post1, vllm-flash-attn 2.5.9.post1, numpy 1.26.4
6. Other relevant environment information [e.g. hardware, CUDA version]: 6 x H100 , CUDA 12.2, Driver 535

**To Reproduce**
Exact steps to reproduce the behavior:
The script I am using is the following : 
```python
from llmcompressor.transformers import SparseAutoModelForCausalLM
from transformers import AutoTokenizer
from datasets import load_dataset
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier

# Model is downloaded using huggingface_cli download 
pretrained_model_dir = "/data/checkpoints/Meta-Llama-3.1-70B-Instruct/"
quantized_model_dir = f"/data/checkpoints/Meta-Llama-3.1-70B-Instruct-INT4-W4A16-G128"
NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048

# Best Practices
# Start with 512 samples for calibration data (increase if accuracy drops)
# Use a sequence length of 2048 as a starting point
# Employ the chat template or instruction template that the model was trained with
# If you’ve fine-tuned a model, consider using a sample of your training data for calibration

# Source : https://docs.vllm.ai/en/latest/quantization/int8.html

## 1. Load the model and tokenizer
model = SparseAutoModelForCausalLM.from_pretrained(
    pretrained_model_dir, device_map="auto", torch_dtype="auto",
)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_dir)

## 2. Prepare Calibration Data
# Load and preprocess the calibration dataset
ds = load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft")
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))

def preprocess(example):
    return {"text": tokenizer.apply_chat_template(example["messages"], tokenize=False)}
ds = ds.map(preprocess)

def tokenize(sample):
    return tokenizer(sample["text"], padding=False, max_length=MAX_SEQUENCE_LENGTH, truncation=True, add_special_tokens=False)
ds = ds.map(tokenize, remove_columns=ds.column_names)

## 3. Apply Quantization
# Configure the quantization algorithms
# Workaround for OOM : https://github.com/vllm-project/llm-compressor/issues/35
recipe = GPTQModifier(targets="Linear", scheme="W4A16", ignore=["lm_head"], sequential_update=True)

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)

# Save the compressed model

model.save_pretrained(quantized_model_dir, save_compressed=True)
tokenizer.save_pretrained(quantized_model_dir)
```

**Errors**
If applicable, add a full print-out of any errors or exceptions that are raised or include screenshots to help explain your problem.

```shell
2024-08-23T14:08:16.959603+0000 | compress_module | INFO - Compressing model.layers.3.model.layers.3.mlp.down_proj...
Traceback (most recent call last):
  File "/workspaces/quantization_toolbox/quantize_int8.py", line 51, in <module>
    oneshot(
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 76, in oneshot
    main(model_args, data_args, training_args)
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 359, in main
    stage_runner.one_shot()
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/transformers/finetune/runner.py", line 171, in one_shot
    self.trainer.one_shot(calibration_data=calib_data, stage=stage)
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/transformers/finetune/session_mixin.py", line 401, in one_shot
    apply(
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/core/session_functions.py", line 184, in apply
    return active_session().apply(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/core/session.py", line 210, in apply
    self.initialize(**kwargs)
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/core/session.py", line 156, in initialize
    mod_data = self._lifecycle.initialize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/core/lifecycle.py", line 126, in initialize
    data = mod.initialize(state=self.state, **extras)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/stage.py", line 124, in initialize
    modifier.initialize(state, **kwargs)
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/modifier.py", line 118, in initialize
    initialized = self.on_initialize(state=state, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/quantization/gptq/base.py", line 188, in on_initialize
    self.apply_compression(calibration_dataloader)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/quantization/gptq/base.py", line 283, in apply_compression
    layer_compressor.compress()
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/utils/layer_compressor.py", line 134, in compress
    self.layer.apply(compress_module)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 894, in apply
    module.apply(fn)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 894, in apply
    module.apply(fn)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 895, in apply
    fn(self)
  File "/home/vscode/py-env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/utils/layer_compressor.py", line 130, in compress_module
    module.compress(**self.args)
  File "/home/vscode/py-env/lib/python3.11/site-packages/llmcompressor/modifiers/quantization/gptq/utils/gptq_wrapper.py", line 128, in compress
    self.H = torch.linalg.cholesky(self.H, upper=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 24340 is not positive-definite).
```

**Comment by robertgshaw2-neuralmagic** [comment]
Can you try setting `dampening_frac=0.1` in your `GPTQModifier`? This will help to limit numerical issues associated with inverting the Hessian in GPTQ, which is the root cause of the issue here.

Additionally -> if you install from source, we made some improvements to the speed of `sequential_update`. You can see an example of how to use it here:
- https://github.com/vllm-project/llm-compressor/blob/main/examples/big_models_with_accelerate/multi_gpu_int8_sequential_update.py

**Comment by lulmer** [comment]
Thank you for the guidance, 
I see that you added a modification on the device_map definition and model type to bfloat16.  I am going to test it

**Comment by lulmer** [comment]
I can confirm setting `dampening_frac=0.1` alongside using the new device map definition suggested on [here](https://github.com/vllm-project/llm-compressor/blob/main/examples/big_models_with_accelerate/multi_gpu_int8_sequential_update.py) solved my problem. 

Thank you @robertgshaw2-neuralmagic for the fast help and have a good day.
