### ISSUE TITLE
[Feature Request] datafree pipeline with layer-by-layer quantization

### ISSUE THREAD

**Issue by mratsim** [vllm-project/llm-compressor#1970]
I am trying to quantize GLM-4.5-Air, GLM-4.5V and finetunes on 2x RTX Pro 6000 to NVFP4A16 (or FP8).

Unfortunately, GLM-4.5-Air with it's 110B parameters requires about 220GB of space and I have 192GB of VRAM.

- The default `datafree` pipeline fails with Cuda OOM.
- Adding `device_map='auto'` to `AutoModelForCausalLM.from_pretrained` still fails, I assume because `huggingface/transformers` doesn't leave enough space for the extra memory needed during quantization.
- `infer_auto_device_map(MODEL_ID, max_memory={0: "85GiB", 1: "85GiB", "cpu": "50GiB"})` fails I think because the model is built differently (error: `AttributeError: 'str' object has no attribute 'named_parameters'`)
- Using `pipeline=sequential` fails because there is no dataset set.

There might be a way to make it work by explicitly picking which layers go to which GPU and CPU but it's quite cumbersome.

Potential solutions:

1. A `calculate_offload_device_map` for datafree
2. A `datafree_sequential` pipeline that does the quantization layer by layer

**Comment by dsikka** [comment]
Hi @mratsim do you mind sharing your full script? I can take a look.

**Comment by mratsim** [comment]
Here you go:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from accelerate import infer_auto_device_map

from llmcompressor import oneshot
from llmcompressor.modifiers.quantization import QuantizationModifier

MODEL_ID = "zai-org/GLM-4.5-Air"
MODEL_OUT = MODEL_ID.split("/")[1] + "-NVFP4A16"

# Load model.
device_map = infer_auto_device_map(MODEL_ID, max_memory={0: "85GiB", 1: "85GiB", "cpu": "50GiB"})
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype="auto", offload_folder = "./offload/", device_map=device_map)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

# Reference: https://github.com/huggingface/transformers/blob/v4.57.1/src/transformers/models/glm4_moe/modeling_glm4_moe.py
recipe = QuantizationModifier(
    # targets="Linear", F.linear is also used for router_logits so it's better to explicitly include what we want to quantize
    targets = [
        "re:.*gate_proj.*", "re:.*up_proj.*", "re:.*down_proj.*",           # MLP projections
        "re:.*k_proj.*", "re:.*q_proj.*", "re:.*v_proj.*", "re:.*o_proj.*", # Attention projections
    ],
    scheme="NVFP4A16",
    ignore=[
        "lm_head",
        "Glm4MoeRMSNorm",
        "re:.*shared_experts.*",
        "re:.*mlp\\.gate$",             # MoE router
        "re:model\\.layers\\.[0-3]\\.", # Keep first 4 blocks
        "re:.*layers\\.46.*"            # MTP layer (Multi-token prediction)
    ]
)

## References
#
# 1. Why Do Some Inputs Break Low-Bit LLM Quantization? (2025)\
#   Ting-Yun Chang, Muru Zhang, Jesse Thomason, Robin Jia\
#   https://arxiv.org/pdf/2506.12044
#
# 2. Examining Post-Training Quantization for Mixture-of-Experts: A Benchmark (2024)\
#   Pingzhi Li, Xiaolong Jin, Yu Cheng, Tianlong Chen\
#   https://arxiv.org/pdf/2406.08155v1
#
# 3. Mixture of Quantized Experts (MoQE): Complementary Effect of Low-bit Quantization and Robustness (2023)\
#   Young Jin Kim, Raffy Fahim, Hany Hassan Awadalla\
#   https://arxiv.org/pdf/2310.02410

oneshot(
    model=model,
    recipe=recipe,
)

# Save to disk in compressed-tensors format.
model.save_pretrained(MODEL_OUT, save_compressed=True)
tokenizer.save_pretrained(MODEL_OUT)
print(f'SUCCESS: files saved in {MODEL_OUT}')
```

This is for tryout 3 with `infer_auto_device_map`, the devicemap can be changed to `'auto'` for tryout 2.

**Comment by kylesayrs** [comment]
I'll also mention that, if you're not calibrating scales, we also have a model free PTQ pathway which does not require a model definition and operates on the safetensors files directly.

https://github.com/vllm-project/llm-compressor/pull/1971

This currently works for FP8 now, currently adding support for NVFP4A16
https://github.com/vllm-project/llm-compressor/pull/1988

**Comment by kylesayrs** [comment]
Those options aside, I think the core issue you're seeing is that LLM Compressor's observers use way more GPU memory than what's required right now. This is because we are using a moving average observer for weights, which stories auxiliary data unnecessarily (this is a known issue that we are actively moving away from).

Could you try again using this branch of compressed tensors? This branch uses the `static_minmax` observer, which only computes a minmax and does not store data about running averages (which are not necessary for weights).
https://github.com/vllm-project/compressed-tensors/pull/489

Doing this should negate the necessity for a "sequential datafree" pipeline, as the data free pipeline already onloads layers and quantizes them on a per-linear-layer basis.

**Comment by mratsim** [comment]
I've been stuck in Python dependency hell.

With latest llmcompressor and your compressed-tensor branch I get this 0.8.1:

<img width="2332" height="89" alt="Image" src="https://github.com/user-attachments/assets/57bf148b-7315-472c-86dc-5dd8d6260ede" />

```toml
dependencies = [
    "compressed-tensors@git+https://github.com/vllm-project/compressed-tensors#egg=kylesayrs/observer-defaults",
    "llmcompressor >= 0.8.1",
    ...
]
```

With latest git #[1c85a66](https://github.com/vllm-project/llm-compressor/commit/1c85a66188ae4c42eeaa50ba65bc87c9ea28b583)
<img width="2701" height="119" alt="Image" src="https://github.com/user-attachments/assets/87e3e456-cb2f-43b4-b587-c99df6fd0357" />

```toml
dependencies = [
    "compressed-tensors@git+https://github.com/vllm-project/compressed-tensors#egg=kylesayrs/observer-defaults",
    "llmcompressor@git+https://github.com/vllm-project/llmcompressor",
    ...
]
```

And I tried creating branch as well before this commit that introduced the min version bump https://github.com/vllm-project/llm-compressor/pull/1904

<img width="2748" height="112" alt="Image" src="https://github.com/user-attachments/assets/099d73c9-0982-4dc2-a611-f3f9825fea76" />

```toml
dependencies = [
    "compressed-tensors@git+https://github.com/vllm-project/compressed-tensors#egg=kylesayrs/observer-defaults",
    "llmcompressor@git+https://github.com/mratsim/llm-compressor#egg=compat-compressed-tensors-observers",
    ...
]
```

I finally resolved it by making that branch the default branch.

Anyway the branch didn't help. It seems like there needs to be a device_map that needs to be computed to leave enough memory for the observers as currently it seems like llmcompressor loads the model with `device_map='auto'` and if the model is bigger than GPU memory calibration fails. This doesn't happen with 'sequential' pipelines like NVFP4 or AWQ:

<img width="1410" height="245" alt="Image" src="https://github.com/user-attachments/assets/aded5a75-38ac-4b13-9f13-7072d4a7af2b" />

**Comment by kylesayrs** [comment]
@mratsim Sorry about that developer experience. As a general rule, dependency mismatches are okay to ignore when you're working with main branches of LC or CT.

> Anyway the branch didn't help. It seems like there needs to be a device_map that needs to be computed to leave enough memory for the observers as currently it seems like llmcompressor loads the model with device_map='auto'

I should have caught this earlier. Your example is quite out of date w.r.t. how LLM Compressor works now. Please load your model on CPU, then allow LLM Compressor to onload the layers one at a time to the GPU automatically.

```python3
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype="auto")  # NO DEVICE MAP
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

...

oneshot(
    model=model,
    recipe=recipe,
)
```

**Comment by mratsim** [comment]
I actually didn't set a device_map, using the new approach, the example with device_map was me trying to work around the OOM.

**Comment by kylesayrs** [comment]
This should be fixed by https://github.com/vllm-project/llm-compressor/pull/2196
