### ISSUE TITLE
[Bug]: CUDA OOM when quantizing 1020B model using GPTQmodifier

### ISSUE THREAD

**Issue by IEI-mjx** [vllm-project/llm-compressor#2167]
### ⚙️ Your current environment

llmcompressor version: v0.7.1
GPU：8XH800 （80GB per gpu）
CPU memory: 4T

### 🐛 Describe the bug

GPU OOM when quantizing 17th/103 layer.

<img width="1694" height="171" alt="Image" src="https://github.com/user-attachments/assets/f0232af2-61b6-4763-9b59-38eadb5bcbe7" />

### 🛠️ Steps to reproduce

Our model have different expert number along 103 layers.
Here is the `per_layer_experts_blocks": [40,48,24,16,24,16,16,24,32,32,24,24,24,40,40,40,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,40,40,40,40,40,40,40,40,32,32,32,32,32,32,24,24,16,8]` 
We set num-calibration from 128 to 16 and set max_length=1024, the quantization process went CUDA OOM at layer1 or layer16 (which has 48 experts).
Is there any solution for this?

**Comment by IEI-mjx** [comment]
As is learned from this [doc](https://docs.vllm.ai/projects/llm-compressor/en/latest/getting-started/compress/#select-a-model-and-dataset), the GPTQ cost about 2*layer GPU memory when doing quantization. But actually, the memory cost is larger than expected?
As is known from this  [video](https://www.youtube.com/live/GrhuqQDmBk8?t=3066s), it is possible to use a smaller granularity to quantize our models, like quantizing several experts rather than one Decoder layer at a time. If that possible, could you please provide an example for this?

**Comment by brian-dellabetta** [comment]
Hi @IEI-mjx , did you try with the `offload_hessians` setting set to True? It may help with GPU VRAM issues, if unset the hessian for each layer is kept on GPU for a given subgraph, which can be quite large for a large MoE model

**Comment by IEI-mjx** [comment]
I solved this by changing the sequential target from Decoder layer to MLP module.

**Comment by kylesayrs** [comment]
@IEI-mjx Awsome, nice job!
