### ISSUE TITLE
CUDA OOM while saving compressed Llama-3.1-70b with AutoModelForCausalLM 

### ISSUE THREAD

**Issue by hibukipanim** [vllm-project/llm-compressor#928]
**Describe the bug**

Trying to quantize `nvidia/Llama-3.1-Nemotron-70B-Instruct-HF` to fp8-dynamic works with `SparseAutoModelForCausalLM`, but when I tried replacing to `AutoModelForCausalLM` as new docs suggest, I get CUDA OOM during "Saving checkpoints shards"

**Environment**

1xA100 80GB
150GB CPU RAM

llmompressor 0.3.0
transformers 4.43.3
torch 2.3.1

**To Reproduce**

Follow the example in `examples/quantization_w8a8_fp8/llama3_example.py` just with `nvidia/Llama-3.1-Nemotron-70B-Instruct-HF`

**Errors**

```
Saving checkpoint shards: 12% ...
...
File "transformers/modeling_utils.py", line 2739, in save_pretrained
  shard_state_dict = get_state_dict_from_offload(module, module_name, shard_state_dict)
...
File "accelerate/utils/modeling", line 321, in set_module_tensor_to_device
  new_value = old_value.to(device)

torch.cuda.OutOfMemoryError: CUDA Out Of Memory. Tried to allocate 448.00 MiB. GPU
```

Thanks! 🙏

**Comment by kylesayrs** [comment]
Can you share your cuda device set up as well as the `model.hf_device_map` of the model after you load it? Thank you

**Comment by hibukipanim** [comment]
Hi thanks,

It's a one A100 80GB card,
Driver version: 535.104.12
CUDA version: 12.2

`model.hd_device_map` is:
- `0` for all layers up until `model.layers.41` (including it) and including `model.embed_tokens`
-  `'cpu'` from `model.layers.42` till `model.layers.79` and including `model.norm`, `model.rotary_emb` and `lm_head`

regarding the stacktrace, I unfortunately can't paste the full stacktrace as the A100 is in an air-gapped environment, I tried my best to type-in manually the indicative bits from the stacktrace in the issue 🙏

**Comment by horheynm** [comment]
@hibukipanim 

Could you share the accelerate you are using? 
Recently there was an update and new version (we are replicated the above using `1.1.1`) will trigger the above error.

While we work on the patch, using the older version (`1.0.1`) will solve the problem. 

The command to install is 
`python3 -m pip install accelerate=1.0.1`

Thank you and let us know!

**Comment by kylesayrs** [comment]
Hi there,

I traced this issue further and found that this is actually related to a very subtle issue caused by https://github.com/huggingface/accelerate/pull/3204 

I've included a detailed description of the bug and its solution in the below PRs. Adopting either of these changes will fix the OOM issue.
* https://github.com/huggingface/transformers/pull/34890
* https://github.com/huggingface/accelerate/pull/3253

Thank you again for reporting this bug! Your efforts helped us identify this and address this quickly! 🙂

**Comment by kylesayrs** [comment]
Hi there,

I traced this issue further and found that this is actually related to a very subtle issue caused by https://github.com/huggingface/accelerate/pull/3204. I've included a detailed description of the bug and its solution in the below PRs. Adopting either of these changes will fix the OOM issue, please let me know otherwise.
* https://github.com/huggingface/transformers/pull/34890
* https://github.com/huggingface/accelerate/pull/3253

Thank you again for reporting this bug! Your efforts helped us identify this and address this quickly! 🙂

**Comment by hibukipanim** [comment]
Hi,

Can confirm I had `accelerate==1.1.1` and after downgrading to `accelerate==1.0.1` it worked with `AutoModelForCausalLM `

Thank you! 🙏

**Comment by hibukipanim** [comment]
Wait, but I noticed something strange ...
The saved model is not quantized when I'm using `AutoModelForCausalLM` ...  it's double the size compared to one saved with `SparseAutoModelForCausalLM` and almost same size as the original ...
despite following `examples/quantization_w8a8_fp8/llama3_example.py`

**Comment by horheynm** [comment]
@hibukipanim Ok let me check on that

**Comment by Inkorak** [comment]
Same problem. OOM with accelerate==1.1.1 and problen with saving with accelerate==1.0.1.

```
from transformers import AutoTokenizer, AutoModelForCausalLM
from llmcompressor.transformers.compression.helpers import calculate_offload_device_map

device_map = calculate_offload_device_map(pretrained_model_dir, reserve_for_hessians=True, num_gpus=1)
model = AutoModelForCausalLM.from_pretrained(
    pretrained_model_dir, device_map=device_map, torch_dtype="auto",
)
tokenizer = AutoTokenizer.from_pretrained(pretrained_model_dir)

DATASET_ID = "HuggingFaceH4/ultrachat_200k"
DATASET_SPLIT = "train_sft"

# Select number of samples. 512 samples is a good place to start.
# Increasing the number of samples can improve accuracy.
NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048

# Load dataset and preprocess.
ds = load_dataset(DATASET_ID, split=DATASET_SPLIT)
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))


def preprocess(example):
    return {
        "text": tokenizer.apply_chat_template(
            example["messages"],
            tokenize=False,
        )
    }


ds = ds.map(preprocess)


# Tokenize inputs.
def tokenize(sample):
    return tokenizer(
        sample["text"],
        padding=False,
        max_length=MAX_SEQUENCE_LENGTH,
        truncation=True,
        add_special_tokens=False,
    )


ds = ds.map(tokenize, remove_columns=ds.column_names)

from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier

# Configure the quantization algorithm to run.
recipe = GPTQModifier(targets="Linear", scheme="W4A16", ignore=["lm_head"])

# Apply quantization.
oneshot(
    model=model, dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
    output_dir=quantized_model_dir,
    save_compressed=True
)

```

**Comment by hibukipanim** [comment]
@horheynm 

reproduced it now with `llmcompressor==0.3.0` and `accelerate==1.0.1` with exactly the same script as in: https://github.com/vllm-project/llm-compressor/blob/a47137d834a2be8f8fcd49458f121b08ba34e2c9/examples/quantization_w8a8_fp8/llama3_example.py (which includes the `oneshot()` call)

the output folder is not quantized:
```
-rw-r--r-- 1 user user  961 Nov 27 09:54 config.json
-rw-r--r-- 1 user user  184 Nov 27 09:54 generation_config.json
-rw-r--r-- 1 user user 4.7G Nov 27 09:54 model-00001-of-00004.safetensors
-rw-r--r-- 1 user user 4.6G Nov 27 09:54 model-00002-of-00004.safetensors
-rw-r--r-- 1 user user 4.6G Nov 27 09:55 model-00003-of-00004.safetensors
-rw-r--r-- 1 user user 1.2G Nov 27 09:55 model-00004-of-00004.safetensors
-rw-r--r-- 1 user user  63K Nov 27 09:55 model.safetensors.index.json
-rw-r--r-- 1 user user  296 Nov 27 09:55 special_tokens_map.json
-rw-r--r-- 1 user user  17M Nov 27 09:55 tokenizer.json
-rw-r--r-- 1 user user  55K Nov 27 09:55 tokenizer_config.json
```

while this is the original:
```
-rwxrwxrwx 1 user user 1.5K Nov 27 09:38 .gitattributes
-rwxrwxrwx 1 user user 7.5K Nov 27 09:38 LICENSE
-rwxrwxrwx 1 user user  44K Nov 27 09:38 README.md
-rwxrwxrwx 1 user user 4.6K Nov 27 09:38 USE_POLICY.md
-rwxrwxrwx 1 user user  855 Nov 27 09:38 config.json
-rwxrwxrwx 1 user user  184 Nov 27 09:38 generation_config.json
-rwxrwxrwx 1 user user 4.7G Nov 27 09:42 model-00001-of-00004.safetensors
-rwxrwxrwx 1 user user 4.7G Nov 27 09:41 model-00002-of-00004.safetensors
-rwxrwxrwx 1 user user 4.6G Nov 27 09:42 model-00003-of-00004.safetensors
-rwxrwxrwx 1 user user 1.1G Nov 27 09:39 model-00004-of-00004.safetensors
-rwxrwxrwx 1 user user  24K Nov 27 09:38 model.safetensors.index.json
-rwxrwxrwx 1 user user  296 Nov 27 09:38 special_tokens_map.json
-rwxrwxrwx 1 user user 8.7M Nov 27 09:38 tokenizer.json
-rwxrwxrwx 1 user user  55K Nov 27 09:38 tokenizer_config.json
```

thanks

**Comment by horheynm** [comment]
Ok cool i will close this for now, if anything new comes up feel free to ping!

Thank you!
